return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"typescript",
			"tsx",
			"javascript",
			"jsx",
			"html",
			"css",
			"scss",
			"json",
			"jsonc",
			"yaml",
			"markdown",
			"markdown_inline",
			"vimdoc",
			"lua",
			"vim",
			"query",
		},
		highlight = { enable = true },
		indent = { enable = true },
		auto_install = true,
	},
}
